# Generated by Django 2.2.7 on 2019-11-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('domain', models.CharField(max_length=128)),
                ('possValues', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=128)),
                ('conditions', models.CharField(max_length=250)),
                ('measurements', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('domain', models.CharField(max_length=128)),
                ('possValues', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('info', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUI.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUI.Condition')),
            ],
        ),
    ]
