# Generated by Django 3.0 on 2019-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=128)),
                ('possValues', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=128)),
                ('possValues', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('info', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=128)),
                ('conditions', models.CharField(max_length=250)),
                ('measurements', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('sequence', 'conditions')},
            },
        ),
    ]
